---
- hosts: all

  tasks:
  - name: "Checking folder"
    stat:
     path: "{{ item }}"
    register: folder_stats
    with_items:
    - "{{ dir }}"
    delegate_to: localhost

  - name: "Creating folder"
    file:
     path: "{{ item.item }}"
     state: directory
    when: item.stat.exists == false
    with_items:
    - "{{ folder_stats.results }}"
    delegate_to: localhost
