---
- name: "Backup configuration from managed hosts"
  hosts: all
  gather_facts: no
  connection: local


  tasks:
  - import_tasks: tasks/get_nexus_cfg_show_cmd.yml

  - import_tasks: tasks/backup_device_cfg.yml
