---
- name: "Get some facts from the device"
  hosts: all

  tasks:
  - name: "Retrieve facts"
    nxos_facts:
     gather_subset: "all"

  - name: "Store Data in File"
    template: "src=templates/facts.j2 dest=outputs/{{ inventory_hostname }}_data.json"
