---
- hosts: all
  gather_facts: no
  connection: local

  tasks:
  - name: "Show command"
    ios_command:
     commands:
      - show version
    register: out

  - debug:
     msg: "{{ out.stdout_lines }}"
