#
# Backup configuration from managed hosts 
#
---
- name: "Save cfg to local file : "
  copy:
   content: "{{ run_cfg.stdout[0] }}"
   dest: "{{ bck_cfg_file }}"
  register: save_cfg
  delegate_to: localhost
