#
# Backup configuration from managed hosts 
#
---
- include_tasks: tasks/create_dir.yml
  with_items: "{{ bck_cfg_dir }}"

- name: "Save cfg to local file : "
  copy:
   content: "{{ run_cfg.stdout[0] }}"
   dest: "{{ bck_cfg_file }}"
  register: save_cfg
  delegate_to: localhost
